### ISSUE TITLE
Please do not rewrite public history

### ISSUE THREAD

**Issue by stopiccot** [xiph/ogg#3]
I'm aware that this github repo is only mirror for git.xiph.org/ogg.git and they had diverged a bit. But it's really bad idea to rewrite history instead of merging.

**Comment by rillian** [comment]
Yeah, sorry about that. Erik merged here instead of pushing upstream, and it looks like the mirror script had failed to propagate the earlier change. However, we strongly prefer linear history for xiph projects, and I don't know of a way to set 'merge.ff only' on github repos, so I force-pushed here to resolve the fork.

I find git copes well enough with history rewrites these days. One can always recover through the reflog if the rebase goes awry.

**Comment by stopiccot** [comment]
I also prefer history to be linear as possible, but merging without touching console is so tempting. You definitely should give it a try.

**Comment by rillian** [comment]
Oh I have. Tempting, as you say. :)
