### ISSUE TITLE
Is there a TODO list in ogg repo?

### ISSUE THREAD

**Issue by willson-chen** [xiph/ogg#57]
New feature or function impovement in TODO List. I think it's a good way to attract more developer.

**Comment by rillian** [comment]
Thanks for your interest!

ogg is a small and mature library. I don't think we want new features. The work is just to maintain support for building in various environments and of course fix any bugs which are reported.

If you want to help with the new release, you can go through the issues and pull requests here and [on gitlab](https://gitlab.xiph.org/xiph/ogg/issues) and see if any can be resolved. That is, determine what this issue is, and if it should be fixed, develop a patch for review or test and comment on any patch which is already submitted.
